runtime: python27
api_version: 1
threadsafe: true

skip_files:
        - ^(.*/)?#.*#$
        - ^(.*/)?.*~$
        - ^(.*/)?.*\.py[co]$
        - ^(.*/)?.*/RCS/.*$
        - ^(.*/)?\..*$
        - node_modules/
        - package.json
        - package-lock.json
        - postcss.config.js
        - public/
        - README.md
        - src/

handlers:
        - url: /
          static_files: dist/index.html
          upload: dist/index.html

        - url: /
          static_dir: dist
